version: '3.8'

services:
  telegram-bot-service:
    build: ./telegram-bot-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - rabbitmq

  core-service:
    build: ./core-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongodb

  rabbitmq:
    build: .
    container_name: rabbitmq
    restart: no
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: password
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_management &&
             rabbitmq-plugins enable rabbitmq_delayed_message_exchange &&
             rabbitmq-server"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: mongo
    container_name: mongodb
    restart: no
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

volumes:
  rabbitmq_data:
  mongo_data: