server:
  port: 8081
spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:app}
    password: ${RABBIT_MQ_PASSWORD:password}
  data:
    mongodb:
      uri: ${MONGO_DB_URI:mongodb://app:password@localhost:27017/tgbot_db?authSource=admin}
