server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: app
    password: password
  data:
    mongodb:
      uri: mongodb://app:password@localhost:27017/tgbot_db?authSource=admin